# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\"\"\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"#\n\rVideoResponse\x12\x12\n\nvideo_data\x18\x01 \x01(\x0c\x32_\n\x10StreamingService\x12K\n\x10StreamAudioVideo\x12\x17.streaming.AudioRequest\x1a\x18.streaming.VideoResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOREQUEST']._serialized_start=30
  _globals['_AUDIOREQUEST']._serialized_end=64
  _globals['_VIDEORESPONSE']._serialized_start=66
  _globals['_VIDEORESPONSE']._serialized_end=101
  _globals['_STREAMINGSERVICE']._serialized_start=103
  _globals['_STREAMINGSERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
